"""
Crypto Latency Trading Bot for Polymarket

Strategy: Exploit price feed latency on 15-minute BTC up/down markets.
- Polymarket has 15-min "BTC Up or Down?" markets (96/day)
- Connect to Binance WebSocket for real-time BTC price (sub-100ms, FREE)
- When BTC clearly moves above/below candle open price, Polymarket odds lag
- Buy the winning side with GTC limit order (maker = zero fees)
- Hold to resolution -> collect $1.00 per share

Key edge: Speed, not prediction. We see the answer on Binance before Polymarket reflects it.

Usage:
    python -m agents.application.crypto_latency_bot --dry-run --max-iterations 5
    python -m agents.application.crypto_latency_bot --live --scan-interval 30
"""

import os
import sys
import json
import time
import asyncio
import logging
import argparse
from collections import deque
from datetime import datetime, timezone, timedelta
from typing import Optional, NamedTuple
from dataclasses import dataclass, asdict

from dotenv import load_dotenv
from pydantic import BaseModel, Field

import websockets

from agents.polymarket.polymarket import Polymarket
from agents.polymarket.gamma import GammaMarketClient
from agents.application.risk_manager import RiskConfig, PortfolioRiskManager
from agents.connectors.telegram_alerts import TelegramAlerter

load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('crypto_latency_trades.log'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


class CryptoLatencyConfig(BaseModel):
    """Configuration for crypto latency trading"""
    min_price_move_pct: float = Field(default=0.15, description="BTC must move 0.15%+ from candle open")
    max_entry_price: float = Field(default=0.65, description="Don't buy above $0.65 on Polymarket")
    min_minutes_remaining: float = Field(default=2.0, description="Don't trade <2 min before resolution")
    max_minutes_remaining: float = Field(default=14.0, description="Don't trade >14 min (too early, uncertain)")
    trade_percent: float = Field(default=0.15, description="15% of cash per trade")
    min_trade_size: float = Field(default=1.0, description="Min trade size in USDC")
    max_trade_size: float = Field(default=10.0, description="Max trade size in USDC")
    max_concurrent_positions: int = Field(default=5, description="Max open positions at once")
    scan_interval: float = Field(default=30, description="Seconds between market scans")
    order_timeout: float = Field(default=30, description="Cancel unfilled limit orders after N seconds")
    asset: str = Field(default="btc", description="Crypto asset to trade (btc, eth, sol)")
    market_windows: list[int] = Field(default=[15], description="Market timeframes in minutes [5, 15]")


class PricePoint(NamedTuple):
    """A timestamped price observation"""
    timestamp: float  # Unix timestamp in seconds
    price: float


@dataclass
class TradeSignal:
    """A trading signal generated by the latency bot"""
    market_id: str
    question: str
    token_id: str
    side: str  # "Up" or "Down"
    suggested_price: float  # Polymarket price to buy at
    btc_price: float
    btc_open_price: float
    move_pct: float
    minutes_remaining: float
    end_date: str
    window_minutes: int = 15


@dataclass
class LatencyTrade:
    """Record of an executed latency trade"""
    timestamp: str
    market_id: str
    question: str
    side: str
    amount: float
    entry_price: float
    expected_payout: float
    expected_profit: float
    btc_price: float
    btc_open_price: float
    move_pct: float
    minutes_remaining: float
    status: str
    order_id: Optional[str] = None
    # Resolution verification fields
    end_date: Optional[str] = None
    resolved_side: Optional[str] = None  # "Up" or "Down" after resolution
    actual_profit: Optional[float] = None  # Real P&L after resolution
    resolution_status: str = "pending"  # "pending", "win", "loss"
    event_slug: Optional[str] = None  # For re-querying resolution


class BinancePriceFeed:
    """
    Real-time BTC price feed from Binance WebSocket.

    Connects to Binance aggTrade stream for sub-100ms price updates.
    Stores prices in a deque for historical lookups (~20 minutes).
    """

    BINANCE_WS_URL = "wss://stream.binance.com:9443/ws/btcusdt@aggTrade"

    def __init__(self, max_history_seconds: int = 1200):
        # ~10 updates/sec * 1200s = 12000 entries
        self._prices: deque[PricePoint] = deque(maxlen=12000)
        self._latest_price: Optional[float] = None
        self._latest_timestamp: float = 0
        self._connected: bool = False
        self._ws_task: Optional[asyncio.Task] = None
        self._reconnect_delay: float = 1.0
        self._max_reconnect_delay: float = 30.0
        self._running: bool = False

    async def start(self):
        """Start the WebSocket connection as a background task."""
        self._running = True
        self._ws_task = asyncio.create_task(self._run_forever())
        # Wait for initial connection (up to 15 seconds)
        for _ in range(150):
            if self._connected and self._latest_price is not None:
                break
            await asyncio.sleep(0.1)
        if self._latest_price is not None:
            logger.info(f"Binance price feed connected. BTC: ${self._latest_price:,.2f}")
        else:
            logger.warning("Binance price feed started but no price received yet")

    async def stop(self):
        """Stop the WebSocket connection."""
        self._running = False
        if self._ws_task:
            self._ws_task.cancel()
            try:
                await self._ws_task
            except asyncio.CancelledError:
                pass
        self._connected = False

    async def _run_forever(self):
        """Maintain WebSocket connection with auto-reconnect."""
        while self._running:
            try:
                async with websockets.connect(
                    self.BINANCE_WS_URL,
                    ping_interval=20,
                    ping_timeout=10,
                ) as ws:
                    self._connected = True
                    self._reconnect_delay = 1.0
                    logger.info("Binance WebSocket connected")

                    async for message in ws:
                        if not self._running:
                            break
                        self._handle_message(message)

            except asyncio.CancelledError:
                break
            except Exception as e:
                self._connected = False
                if self._running:
                    logger.warning(f"Binance WS error: {e}. Reconnecting in {self._reconnect_delay:.0f}s...")
                    await asyncio.sleep(self._reconnect_delay)
                    self._reconnect_delay = min(self._reconnect_delay * 2, self._max_reconnect_delay)

    def _handle_message(self, raw: str):
        """Parse an aggTrade message and store the price."""
        try:
            data = json.loads(raw)
            price = float(data["p"])
            # Binance timestamp is in milliseconds
            ts = float(data["T"]) / 1000.0
            point = PricePoint(timestamp=ts, price=price)
            self._prices.append(point)
            self._latest_price = price
            self._latest_timestamp = ts
        except (KeyError, ValueError, json.JSONDecodeError):
            pass

    def get_price(self) -> Optional[tuple[float, float]]:
        """
        Get the latest BTC price.

        Returns:
            (price, timestamp) or None if no data
        """
        if self._latest_price is None:
            return None
        return (self._latest_price, self._latest_timestamp)

    def get_price_at(self, target_ts: float) -> Optional[float]:
        """
        Look up the BTC price closest to a given timestamp.

        Uses binary-ish search over the stored deque.

        Args:
            target_ts: Unix timestamp in seconds

        Returns:
            Price at that time, or None if no data near that time
        """
        if not self._prices:
            return None

        # If target is before our history, return earliest
        if target_ts <= self._prices[0].timestamp:
            return self._prices[0].price

        # If target is after our latest, return latest
        if target_ts >= self._prices[-1].timestamp:
            return self._prices[-1].price

        # Linear scan from the end (most recent) for efficiency
        # since we usually look up recent timestamps
        best_price = None
        best_diff = float('inf')
        for point in reversed(self._prices):
            diff = abs(point.timestamp - target_ts)
            if diff < best_diff:
                best_diff = diff
                best_price = point.price
            elif diff > best_diff:
                # Moving away from target, stop
                break

        return best_price

    @property
    def connected(self) -> bool:
        return self._connected and self._latest_price is not None


class CryptoLatencyBot:
    """
    Crypto Latency Trading Bot for Polymarket.

    Exploits the price feed latency between Binance (real-time BTC)
    and Polymarket (15-minute up/down markets).
    """

    def __init__(
        self,
        config: Optional[CryptoLatencyConfig] = None,
        risk_config: Optional[RiskConfig] = None,
        dry_run: bool = True,
        simulated_balance: Optional[float] = None,
    ):
        self.config = config or CryptoLatencyConfig()
        self.dry_run = dry_run
        self.simulated_balance = simulated_balance

        # Core services
        self.polymarket = Polymarket()
        self.gamma = GammaMarketClient()
        self.risk_config = risk_config or RiskConfig()
        self.risk_manager = PortfolioRiskManager(self.polymarket, self.risk_config)
        self.telegram = TelegramAlerter()

        # Binance price feed
        self.price_feed = BinancePriceFeed()

        # Trading state
        self.active_orders: dict[str, dict] = {}  # order_id -> order info
        self.traded_markets: set[str] = set()  # market IDs already traded this session
        self.position_count: int = 0
        self.total_trades: int = 0
        self.successful_trades: int = 0
        self.failed_trades: int = 0
        self.trade_history: list[LatencyTrade] = []
        self.initial_balance: Optional[float] = None
        self.simulated_pnl: float = 0.0

        # Resolution verification
        self.pending_resolutions: list[LatencyTrade] = []  # Trades awaiting resolution
        self.verified_wins: int = 0
        self.verified_losses: int = 0
        self.verified_pnl: float = 0.0  # Actual P&L from resolved trades

        logger.info(f"CryptoLatencyBot initialized (dry_run={dry_run}, asset={self.config.asset})")
        logger.info(f"Config: {self.config.model_dump()}")

    def get_balance(self) -> float:
        """Get current USDC balance."""
        if self.simulated_balance is not None:
            return self.simulated_balance + self.simulated_pnl
        return self.risk_manager.get_balance()

    def find_active_markets(self) -> list[dict]:
        """Find active crypto markets across all configured timeframes."""
        all_markets = []
        for window in self.config.market_windows:
            try:
                markets = self.gamma.get_crypto_markets(
                    asset=self.config.asset,
                    window_minutes=window,
                )
                all_markets.extend(markets)
            except Exception as e:
                logger.error(f"Failed to fetch {window}-min markets: {e}")
        return all_markets

    def get_candle_open_price(self, market: dict) -> Optional[float]:
        """
        Derive the BTC price at the start of a market candle.

        The market endDate minus window_minutes = candle start time.
        Look up BTC price at that timestamp from our stored history.
        """
        end_date_str = market.get("endDate", "")
        if not end_date_str:
            return None

        window_minutes = market.get("_window_minutes", 15)
        try:
            end_date = datetime.fromisoformat(end_date_str.replace("Z", "+00:00"))
            start_time = end_date - timedelta(minutes=window_minutes)
            start_ts = start_time.timestamp()
            return self.price_feed.get_price_at(start_ts)
        except Exception:
            return None

    def _get_required_move_pct(self, minutes_remaining: float, window_minutes: int = 15) -> float:
        """
        Time-scaled entry threshold: require bigger moves early in candle.

        Rationale: Early in the candle there's more time for price to reverse,
        so we need stronger conviction. Near the close, a smaller move is
        already nearly locked in.

        15-min scale:
            12+ min left → 0.40% move required
             8  min left → 0.30%
             5  min left → 0.20%
             2  min left → 0.15% (config minimum)

        5-min scale (proportionally scaled):
             4+ min left → 0.40%
           2.5  min left → 0.25%
           1.5  min left → 0.15%
             0  min left → 0.10%
        """
        if window_minutes <= 5:
            if minutes_remaining >= 4:
                return 0.40
            elif minutes_remaining >= 2.5:
                return 0.25
            elif minutes_remaining >= 1.5:
                return 0.15
            else:
                return 0.10
        else:
            # 15-min (default)
            if minutes_remaining >= 12:
                return 0.40
            elif minutes_remaining >= 8:
                return 0.30
            elif minutes_remaining >= 5:
                return 0.20
            else:
                return self.config.min_price_move_pct  # 0.15

    def _check_trend_filter(self, winning_side: str) -> bool:
        """
        Trend filter: only trade WITH the macro trend, never against it.

        Checks BTC direction over the last 10 minutes of price history.
        If BTC is trending up, only allow "Up" trades. If trending down,
        only allow "Down" trades. If flat/unclear, allow either.

        Returns True if the trade is aligned with the trend (or trend is unclear).
        """
        prices = self.price_feed._prices
        if len(prices) < 100:
            # Not enough data to determine trend, allow trade
            return True

        now_ts = prices[-1].timestamp
        # Look back 10 minutes (600 seconds)
        lookback_ts = now_ts - 600

        # Find the price ~10 minutes ago
        trend_start_price = None
        for point in prices:
            if point.timestamp >= lookback_ts:
                trend_start_price = point.price
                break

        if trend_start_price is None or trend_start_price <= 0:
            return True

        trend_now = prices[-1].price
        trend_pct = ((trend_now - trend_start_price) / trend_start_price) * 100.0

        # Only block if there's a clear opposing trend (> 0.10% in the wrong direction)
        if winning_side == "Up" and trend_pct < -0.10:
            logger.info(f"  TREND FILTER: Blocked {winning_side} bet — BTC 10min trend is {trend_pct:+.3f}% (bearish)")
            return False
        if winning_side == "Down" and trend_pct > 0.10:
            logger.info(f"  TREND FILTER: Blocked {winning_side} bet — BTC 10min trend is {trend_pct:+.3f}% (bullish)")
            return False

        logger.info(f"  Trend check OK: {winning_side} aligns with 10min trend ({trend_pct:+.3f}%)")
        return True

    def _check_orderbook_price(self, token_id: str) -> Optional[float]:
        """
        Check the real CLOB best ask price for a token.

        The Gamma API `outcomePrices` can be stale. The CLOB order book
        shows the actual current ask price. If the winning side is
        already expensive on the book, the edge is gone.

        Returns the best ask price, or None if the check fails.
        """
        try:
            return self.polymarket.get_best_ask(token_id)
        except Exception as e:
            logger.debug(f"Order book price check failed: {e}")
            return None

    def evaluate_opportunity(self, market: dict) -> Optional[TradeSignal]:
        """
        Evaluate a market for a latency trading opportunity.

        Checks:
        1. Minutes remaining in valid window
        2. BTC has moved enough from candle open (time-scaled threshold)
        3. Trend filter: only trade WITH the 10-min BTC trend
        4. Polymarket price for winning side is < max_entry_price
        5. Order book price verification (real price, not stale API)
        """
        market_id = str(market.get("id", ""))
        window_minutes = market.get("_window_minutes", 15)

        # Skip if already traded
        if market_id in self.traded_markets:
            return None

        # Skip if on cooldown
        if self.risk_manager.is_market_on_cooldown(market_id):
            return None

        # Check minutes remaining
        end_date_str = market.get("endDate", "")
        if not end_date_str:
            return None

        try:
            end_date = datetime.fromisoformat(end_date_str.replace("Z", "+00:00"))
        except Exception:
            return None

        now = datetime.now(timezone.utc)
        minutes_remaining = (end_date - now).total_seconds() / 60.0

        if minutes_remaining < self.config.min_minutes_remaining:
            return None
        if minutes_remaining > self.config.max_minutes_remaining:
            return None

        # Get current BTC price
        price_data = self.price_feed.get_price()
        if price_data is None:
            return None
        btc_now, _ = price_data

        # Get BTC price at candle open
        btc_open = self.get_candle_open_price(market)
        if btc_open is None or btc_open <= 0:
            return None

        # Calculate move percentage
        move_pct = ((btc_now - btc_open) / btc_open) * 100.0

        # TIME-SCALED THRESHOLD: require bigger moves early in candle
        required_move = self._get_required_move_pct(minutes_remaining, window_minutes)
        if abs(move_pct) < required_move:
            return None

        # Determine direction: positive move = "Up" wins, negative = "Down" wins
        question = market.get("question", "")
        if move_pct > 0:
            winning_side = "Up"
        else:
            winning_side = "Down"

        # TREND FILTER: only trade WITH the macro trend
        if not self._check_trend_filter(winning_side):
            return None

        # Get token IDs and prices
        clob_token_ids = market.get("clobTokenIds", "[]")
        if isinstance(clob_token_ids, str):
            clob_token_ids = json.loads(clob_token_ids)

        outcome_prices = market.get("outcomePrices", "[]")
        if isinstance(outcome_prices, str):
            outcome_prices = json.loads(outcome_prices)

        if len(clob_token_ids) < 2 or len(outcome_prices) < 2:
            return None

        # Determine which token to buy
        # outcomes[0] is usually "Up" / "Yes", outcomes[1] is "Down" / "No"
        outcomes = market.get("outcomes", "[]")
        if isinstance(outcomes, str):
            outcomes = json.loads(outcomes)

        # Find the winning token
        token_idx = None
        for i, outcome in enumerate(outcomes):
            outcome_lower = outcome.lower()
            if winning_side.lower() in outcome_lower or \
               (winning_side == "Up" and ("yes" in outcome_lower or "up" in outcome_lower or "higher" in outcome_lower)) or \
               (winning_side == "Down" and ("no" in outcome_lower or "down" in outcome_lower or "lower" in outcome_lower)):
                token_idx = i
                break

        if token_idx is None:
            # Default: Up=0, Down=1
            token_idx = 0 if winning_side == "Up" else 1

        token_id = clob_token_ids[token_idx]
        polymarket_price = float(outcome_prices[token_idx])

        # ORDER BOOK PRICE CHECK: use real CLOB price instead of stale API price
        real_price = self._check_orderbook_price(token_id)
        if real_price is not None:
            if abs(real_price - polymarket_price) > 0.05:
                logger.info(f"  Price divergence: API=${polymarket_price:.4f} vs Book=${real_price:.4f}")
            # Use the real price for entry decision
            polymarket_price = real_price

        # Check Polymarket price is still cheap enough
        if polymarket_price >= self.config.max_entry_price:
            logger.info(f"  SKIP: {winning_side} price ${polymarket_price:.4f} >= max ${self.config.max_entry_price}")
            return None

        # Also skip if price is too low (might indicate the market is illiquid or broken)
        if polymarket_price < 0.30:
            return None

        return TradeSignal(
            market_id=market_id,
            question=question,
            token_id=token_id,
            side=winning_side,
            suggested_price=polymarket_price,
            btc_price=btc_now,
            btc_open_price=btc_open,
            move_pct=move_pct,
            minutes_remaining=minutes_remaining,
            end_date=end_date_str,
            window_minutes=window_minutes,
        )

    async def execute_trade(self, signal: TradeSignal) -> Optional[LatencyTrade]:
        """
        Execute a latency trade.

        Places a GTC limit order, waits for fill, cancels if timeout.
        """
        balance = self.get_balance()
        trade_size = balance * self.config.trade_percent
        trade_size = min(trade_size, self.config.max_trade_size)
        trade_size = max(trade_size, self.config.min_trade_size)

        if trade_size > balance:
            logger.warning(f"Insufficient balance: ${balance:.2f} < min ${self.config.min_trade_size}")
            return None

        # Check concurrent position limit
        if self.position_count >= self.config.max_concurrent_positions:
            logger.info(f"At max positions ({self.position_count}/{self.config.max_concurrent_positions})")
            return None

        # Re-fetch best ask right before ordering for freshest price
        best_ask = self.polymarket.get_best_ask(signal.token_id)
        order_price = best_ask if best_ask and best_ask <= self.config.max_entry_price else signal.suggested_price
        logger.info(f"Order pricing: best_ask=${best_ask}, suggested=${signal.suggested_price:.4f}, using=${order_price:.4f}")

        # Calculate shares and expected profit
        shares = trade_size / order_price
        expected_payout = shares  # Each share pays $1.00 at resolution
        expected_profit = expected_payout - trade_size  # No fees for maker orders!

        trade = LatencyTrade(
            timestamp=datetime.now(timezone.utc).isoformat(),
            market_id=signal.market_id,
            question=signal.question,
            side=signal.side,
            amount=trade_size,
            entry_price=order_price,
            expected_payout=expected_payout,
            expected_profit=expected_profit,
            btc_price=signal.btc_price,
            btc_open_price=signal.btc_open_price,
            move_pct=signal.move_pct,
            minutes_remaining=signal.minutes_remaining,
            status="PENDING",
        )

        logger.info(f"\n{'='*60}")
        logger.info("CRYPTO LATENCY TRADE SIGNAL")
        logger.info(f"Market: {signal.question[:60]}")
        logger.info(f"Side: {signal.side} @ ${order_price:.4f}")
        logger.info(f"BTC: ${signal.btc_price:,.2f} (open: ${signal.btc_open_price:,.2f}, move: {signal.move_pct:+.3f}%)")
        logger.info(f"Time remaining: {signal.minutes_remaining:.1f} min")
        logger.info(f"Trade: ${trade_size:.2f} -> {shares:.1f} shares -> ${expected_payout:.2f} payout")
        logger.info(f"Expected profit: ${expected_profit:.2f} (zero fees!)")
        logger.info(f"{'='*60}\n")

        if self.dry_run:
            logger.info("[DRY RUN] Trade simulated (not placed on chain)")
            trade.status = "DRY_RUN"
            trade.end_date = signal.end_date
            # Derive event slug for resolution checking
            try:
                end_dt = datetime.fromisoformat(signal.end_date.replace("Z", "+00:00"))
                start_ts = int((end_dt - timedelta(minutes=signal.window_minutes)).timestamp())
                trade.event_slug = f"{self.config.asset.lower()}-updown-{signal.window_minutes}m-{start_ts}"
            except Exception:
                trade.event_slug = None
            self.successful_trades += 1
            self.traded_markets.add(signal.market_id)
            # Don't add profit yet — wait for resolution verification
            self.pending_resolutions.append(trade)
            logger.info(f"[DRY RUN] Trade queued for resolution verification (resolves at {signal.end_date})")
        else:
            try:
                logger.warning(">>> PLACING LIVE LIMIT ORDER <<<")

                # Place GTC limit order at best ask for immediate fill
                order_response = self.polymarket.execute_limit_buy(
                    token_id=signal.token_id,
                    price=order_price,
                    size=round(shares, 2),
                )

                order_id = None
                if isinstance(order_response, dict):
                    order_id = order_response.get("orderID") or order_response.get("id")
                elif isinstance(order_response, str):
                    order_id = order_response

                trade.order_id = str(order_id) if order_id else None
                logger.info(f"Order placed: {order_id}")

                # Wait for fill or timeout
                filled = await self._wait_for_fill(order_id, signal.token_id)

                if filled:
                    trade.status = "FILLED"
                    trade.end_date = signal.end_date
                    # Derive event slug for resolution checking
                    try:
                        end_dt = datetime.fromisoformat(signal.end_date.replace("Z", "+00:00"))
                        start_ts = int((end_dt - timedelta(minutes=signal.window_minutes)).timestamp())
                        trade.event_slug = f"{self.config.asset.lower()}-updown-{signal.window_minutes}m-{start_ts}"
                    except Exception:
                        trade.event_slug = None
                    self.successful_trades += 1
                    self.position_count += 1
                    self.traded_markets.add(signal.market_id)
                    self.pending_resolutions.append(trade)
                    logger.info(f"Order FILLED! Queued for resolution verification.")
                else:
                    # Cancel unfilled order
                    if order_id:
                        try:
                            self.polymarket.cancel_order(str(order_id))
                            logger.info(f"Order cancelled after {self.config.order_timeout}s timeout")
                        except Exception as e:
                            logger.warning(f"Failed to cancel order: {e}")
                    trade.status = "TIMEOUT_CANCELLED"
                    self.failed_trades += 1

            except Exception as e:
                logger.error(f"Trade execution failed: {e}")
                trade.status = "FAILED"
                self.failed_trades += 1
                self.risk_manager.record_failed_market(signal.market_id)

        self.total_trades += 1
        self.trade_history.append(trade)
        self._log_trade(trade)

        # Send Telegram alert for fills
        if trade.status in ("FILLED", "DRY_RUN"):
            try:
                self.telegram.send_message_sync(
                    f"{'[DRY] ' if self.dry_run else ''}<b>LATENCY {trade.status} [{signal.window_minutes}m]</b>\n\n"
                    f"{signal.question[:50]}\n"
                    f"BUY {signal.side} @ ${order_price:.4f}\n"
                    f"BTC: ${signal.btc_price:,.2f} ({signal.move_pct:+.3f}%)\n"
                    f"Cost: ${trade_size:.2f} | Shares: {shares:.1f}\n"
                    f"Payout if win: ${expected_payout:.2f} (+${expected_profit:.2f})\n"
                    f"Time left: {signal.minutes_remaining:.1f} min\n"
                )
            except Exception as e:
                logger.warning(f"Telegram alert failed: {e}")

        return trade

    async def _wait_for_fill(self, order_id: Optional[str], token_id: str) -> bool:
        """Wait for a limit order to fill, up to order_timeout seconds."""
        if not order_id:
            return False

        start = time.time()
        while (time.time() - start) < self.config.order_timeout:
            try:
                order = self.polymarket.get_order(str(order_id))
                status = ""
                if isinstance(order, dict):
                    status = order.get("status", "").lower()
                elif isinstance(order, str):
                    status = order.lower()

                if "matched" in status or "filled" in status:
                    return True
                if "cancelled" in status or "canceled" in status:
                    return False
            except Exception:
                pass
            await asyncio.sleep(1.0)

        return False

    def _log_trade(self, trade: LatencyTrade):
        """Log trade to file."""
        try:
            with open('crypto_latency_trades.log', 'a') as f:
                f.write(json.dumps(asdict(trade)) + '\n')
        except Exception as e:
            logger.error(f"Failed to log trade: {e}")

    async def check_resolutions(self):
        """
        Check if any pending dry-run trades have resolved.

        Queries the Gamma API for each pending trade's market to see
        if it resolved Up or Down, then scores our prediction.
        """
        if not self.pending_resolutions:
            return

        now = datetime.now(timezone.utc)
        still_pending = []

        for trade in self.pending_resolutions:
            # Check if endDate has passed (with 60s buffer for resolution delay)
            if not trade.end_date:
                still_pending.append(trade)
                continue

            try:
                end_dt = datetime.fromisoformat(trade.end_date.replace("Z", "+00:00"))
            except Exception:
                still_pending.append(trade)
                continue

            if now < end_dt + timedelta(seconds=60):
                still_pending.append(trade)
                continue

            # Market should have resolved — check outcome
            resolved_side = await self._get_resolved_side(trade)

            if resolved_side is None:
                # Polymarket can take 10-20 min to mark these as closed.
                # Keep checking for up to 30 minutes past endDate.
                if now < end_dt + timedelta(minutes=30):
                    still_pending.append(trade)
                else:
                    logger.warning(f"Could not verify resolution after 30 min for {trade.question[:50]}")
                    trade.resolution_status = "unknown"
                continue

            trade.resolved_side = resolved_side
            won = (trade.side.lower() == resolved_side.lower())

            if won:
                trade.resolution_status = "win"
                trade.actual_profit = trade.expected_profit
                self.verified_wins += 1
                self.verified_pnl += trade.actual_profit
                if self.simulated_balance is not None:
                    self.simulated_pnl += trade.actual_profit
                logger.info(
                    f"VERIFIED WIN: {trade.question[:50]} | "
                    f"Bet {trade.side}, resolved {resolved_side} | "
                    f"Profit: +${trade.actual_profit:.2f}"
                )
            else:
                trade.resolution_status = "loss"
                trade.actual_profit = -trade.amount  # Lost the entire bet
                self.verified_losses += 1
                self.verified_pnl += trade.actual_profit
                if self.simulated_balance is not None:
                    self.simulated_pnl += trade.actual_profit
                logger.info(
                    f"VERIFIED LOSS: {trade.question[:50]} | "
                    f"Bet {trade.side}, resolved {resolved_side} | "
                    f"Loss: -${trade.amount:.2f}"
                )

            # Update trade log
            self._log_trade(trade)

            # Telegram notification for resolution
            total_resolved = self.verified_wins + self.verified_losses
            win_rate = self.verified_wins / total_resolved * 100 if total_resolved > 0 else 0
            current_balance = self.get_balance()
            try:
                self.telegram.send_message_sync(
                    f"{'[DRY] ' if self.dry_run else ''}<b>RESOLUTION {'WIN' if won else 'LOSS'}</b>\n\n"
                    f"{trade.question[:50]}\n"
                    f"Bet: {trade.side} | Result: {resolved_side}\n"
                    f"This trade: ${trade.actual_profit:+.2f}\n\n"
                    f"Record: {self.verified_wins}W/{self.verified_losses}L ({win_rate:.0f}%)\n"
                    f"Session P&L: ${self.verified_pnl:+.2f}\n"
                    f"Balance: ${current_balance:.2f}\n"
                )
            except Exception:
                pass

        self.pending_resolutions = still_pending

    async def _get_resolved_side(self, trade: LatencyTrade) -> Optional[str]:
        """Query Gamma API to determine which side won (Up or Down)."""
        import httpx as _httpx

        slug = trade.event_slug
        if not slug:
            return None

        try:
            response = _httpx.get(
                "https://gamma-api.polymarket.com/events",
                params={"slug": slug},
                timeout=10,
            )
            if response.status_code != 200:
                return None

            events = response.json()
            if not events:
                return None

            event = events[0]

            for market in event.get("markets", []):
                outcome_prices = market.get("outcomePrices", "[]")
                if isinstance(outcome_prices, str):
                    outcome_prices = json.loads(outcome_prices)

                outcomes = market.get("outcomes", "[]")
                if isinstance(outcomes, str):
                    outcomes = json.loads(outcomes)

                if len(outcome_prices) >= 2 and len(outcomes) >= 2:
                    # Winner has price >= 0.95 (allow for slight delay before hitting 1.0)
                    # Also check that the other side is near 0 to confirm resolution
                    prices = [float(p) for p in outcome_prices]
                    if max(prices) >= 0.95 and min(prices) <= 0.05:
                        winner_idx = prices.index(max(prices))
                        return outcomes[winner_idx]  # "Up" or "Down"

            return None

        except Exception as e:
            logger.debug(f"Error checking resolution for {slug}: {e}")
            return None

    def print_status(self):
        """Print current status."""
        balance = self.get_balance()
        btc_data = self.price_feed.get_price()
        btc_str = f"${btc_data[0]:,.2f}" if btc_data else "N/A"

        logger.info(f"\n{'='*50}")
        logger.info("CRYPTO LATENCY BOT STATUS")
        logger.info(f"{'='*50}")
        logger.info(f"BTC Price: {btc_str}")
        logger.info(f"Balance: ${balance:.2f}")
        if self.initial_balance:
            pnl = balance - self.initial_balance
            logger.info(f"Session P&L: ${pnl:+.2f}")
        logger.info(f"Trades: {self.total_trades} (fills: {self.successful_trades}, failed: {self.failed_trades})")
        logger.info(f"Open positions: {self.position_count}/{self.config.max_concurrent_positions}")

        # Resolution verification scoreboard
        total_resolved = self.verified_wins + self.verified_losses
        pending = len(self.pending_resolutions)
        if total_resolved > 0 or pending > 0:
            win_rate = self.verified_wins / total_resolved * 100 if total_resolved > 0 else 0
            logger.info(f"--- Resolution Scoreboard ---")
            logger.info(f"Verified: {self.verified_wins}W / {self.verified_losses}L ({win_rate:.0f}% win rate)")
            logger.info(f"Verified P&L: ${self.verified_pnl:+.2f}")
            logger.info(f"Awaiting resolution: {pending}")

        logger.info(f"Mode: {'DRY RUN' if self.dry_run else 'LIVE'}")
        logger.info(f"{'='*50}\n")

    async def run(self, scan_interval: Optional[float] = None, max_iterations: Optional[int] = None):
        """
        Main async event loop.

        1. Start Binance WebSocket
        2. Poll Gamma for 15-min markets every scan_interval seconds
        3. Evaluate each market for latency opportunity
        4. Execute trades when signals appear
        """
        interval = scan_interval or self.config.scan_interval

        logger.info(f"\n{'='*60}")
        logger.info("STARTING CRYPTO LATENCY BOT")
        windows_str = "/".join(f"{w}m" for w in self.config.market_windows)
        logger.info(f"Asset: {self.config.asset.upper()} | Windows: {windows_str}")
        logger.info(f"Scan interval: {interval}s")
        logger.info(f"Mode: {'DRY RUN' if self.dry_run else 'LIVE TRADING'}")
        logger.info(f"Entry threshold: BTC move > {self.config.min_price_move_pct}%, Polymarket < ${self.config.max_entry_price}")
        logger.info(f"{'='*60}\n")

        if not self.dry_run:
            logger.warning("=" * 60)
            logger.warning("WARNING: LIVE TRADING MODE - REAL FUNDS AT RISK")
            logger.warning("=" * 60)
            await asyncio.sleep(5)

        # Initialize balance
        balance = self.get_balance()
        self.initial_balance = balance
        logger.info(f"Starting balance: ${balance:.2f}")

        if balance < self.config.min_trade_size:
            logger.error(f"Balance ${balance:.2f} below min trade size ${self.config.min_trade_size}")
            return

        # Start Binance price feed
        logger.info("Connecting to Binance WebSocket...")
        await self.price_feed.start()

        if not self.price_feed.connected:
            logger.error("Failed to connect to Binance. Exiting.")
            return

        # Send Telegram startup
        try:
            self.telegram.send_message_sync(
                f"<b>CRYPTO LATENCY BOT STARTED</b>\n\n"
                f"Mode: {'DRY RUN' if self.dry_run else 'LIVE'}\n"
                f"Asset: {self.config.asset.upper()}\n"
                f"Balance: ${balance:.2f}\n"
                f"Scan interval: {interval}s\n"
            )
        except Exception:
            pass

        iteration = 0

        try:
            while max_iterations is None or iteration < max_iterations:
                iteration += 1
                logger.info(f"\n--- Scan {iteration} ---")

                # Check Binance connection
                if not self.price_feed.connected:
                    logger.warning("Binance disconnected, waiting for reconnect...")
                    await asyncio.sleep(5)
                    continue

                btc_data = self.price_feed.get_price()
                if btc_data:
                    logger.info(f"BTC: ${btc_data[0]:,.2f}")

                # Find active markets across all configured timeframes
                markets = self.find_active_markets()
                windows_str = "/".join(f"{w}m" for w in self.config.market_windows)
                logger.info(f"Found {len(markets)} active {windows_str} {self.config.asset.upper()} markets")

                # Evaluate each market
                signals = []
                for market in markets:
                    q = market.get("question", "")[:50]
                    wm = market.get("_window_minutes", 15)
                    end_str = market.get("endDate", "")
                    try:
                        end_dt = datetime.fromisoformat(end_str.replace("Z", "+00:00"))
                        mins_left = (end_dt - datetime.now(timezone.utc)).total_seconds() / 60.0
                    except Exception:
                        mins_left = -1
                    btc_open = self.get_candle_open_price(market)
                    if btc_data and btc_open:
                        mv = ((btc_data[0] - btc_open) / btc_open) * 100
                        req = self._get_required_move_pct(mins_left, wm)
                        logger.info(f"  [{wm}m] {q} | {mins_left:.1f}min | move {mv:+.3f}% (need {req:.2f}%)")
                    signal = self.evaluate_opportunity(market)
                    if signal:
                        signals.append(signal)

                if signals:
                    # Sort by move strength (strongest signal first)
                    signals.sort(key=lambda s: abs(s.move_pct), reverse=True)
                    logger.info(f"Found {len(signals)} trade signals!")
                    for sig in signals:
                        logger.info(f"  {sig.side} @ ${sig.suggested_price:.4f} | BTC {sig.move_pct:+.3f}% | {sig.minutes_remaining:.1f}min left")

                    # Execute best signal
                    best = signals[0]
                    await self.execute_trade(best)
                else:
                    logger.info("No trade signals this scan")

                # Check if any previous trades have resolved
                await self.check_resolutions()

                self.print_status()

                # Wait for next scan
                if max_iterations is None or iteration < max_iterations:
                    logger.info(f"Next scan in {interval}s...")
                    await asyncio.sleep(interval)

        except KeyboardInterrupt:
            logger.info("\nBot stopped by user")
        except Exception as e:
            logger.error(f"Error in main loop: {e}", exc_info=True)
        finally:
            await self.price_feed.stop()
            self.print_status()

            # Send shutdown message
            try:
                self.telegram.send_message_sync(
                    f"<b>CRYPTO LATENCY BOT STOPPED</b>\n\n"
                    f"Trades: {self.total_trades}\n"
                    f"Fills: {self.successful_trades}\n"
                    f"Balance: ${self.get_balance():.2f}\n"
                )
            except Exception:
                pass

            logger.info("Crypto latency bot stopped")


def main():
    parser = argparse.ArgumentParser(description='Polymarket Crypto Latency Bot')
    parser.add_argument('--dry-run', action='store_true', default=True,
                        help='Run in dry-run mode (no real trades)')
    parser.add_argument('--live', action='store_true',
                        help='Run in live mode (REAL TRADES)')
    parser.add_argument('--scan-interval', type=float, default=30,
                        help='Seconds between scans (default: 30)')
    parser.add_argument('--max-iterations', type=int, default=None,
                        help='Maximum scan iterations')
    parser.add_argument('--simulated-balance', type=float, default=None,
                        help='Simulated balance for dry-run testing')
    parser.add_argument('--min-move', type=float, default=None,
                        help='Min BTC move %% to trigger trade (default: 0.15)')
    parser.add_argument('--max-entry', type=float, default=None,
                        help='Max Polymarket entry price (default: 0.65)')
    parser.add_argument('--asset', type=str, default='btc',
                        help='Crypto asset to trade (btc, eth, sol)')
    parser.add_argument('--windows', type=str, default=None,
                        help='Market timeframes in minutes, comma-separated (e.g., "5,15")')

    args = parser.parse_args()

    config_kwargs = {}
    if args.min_move is not None:
        config_kwargs['min_price_move_pct'] = args.min_move
    if args.max_entry is not None:
        config_kwargs['max_entry_price'] = args.max_entry
    if args.asset:
        config_kwargs['asset'] = args.asset
    if args.windows:
        config_kwargs['market_windows'] = [int(w.strip()) for w in args.windows.split(',')]

    config = CryptoLatencyConfig(**config_kwargs)
    risk_config = RiskConfig()
    dry_run = not args.live

    bot = CryptoLatencyBot(
        config=config,
        risk_config=risk_config,
        dry_run=dry_run,
        simulated_balance=args.simulated_balance,
    )

    asyncio.run(bot.run(
        scan_interval=args.scan_interval,
        max_iterations=args.max_iterations,
    ))


if __name__ == "__main__":
    main()
